### ISSUE TITLE
Can you give the results of the same image to inpaint using different reference image? 

### ISSUE THREAD

**Issue by wwqLearning** [zhangqianhui/Exemplar-GAN-Eye-Inpainting-Tensorflow#1]

**Comment by zhangqianhui** [comment]
you can download the original training data and test using different reference image.
But the code for reading data need to be changed.

**Comment by zhangqianhui** [comment]
hello, I have updated the code.

**Comment by wwqLearning** [comment]
Thanks. I have read the results. And I find that the eyes of results have less relationships with the reference celeb, can you explain why?

**Comment by zhangqianhui** [comment]
this is  not final result.

**Comment by zhangqianhui** [comment]
@wwqLearning  I have shown the inpainted results with difference reference images in test
