### ISSUE TITLE
Hello！I have encountered some problems when running your new code.

### ISSUE THREAD

**Issue by SunHu1** [zhangqianhui/Exemplar-GAN-Eye-Inpainting-Tensorflow#2]
some values of v[i]['opened'] may be None，and the following  is the question cues
  File "E:\gan\cod\Exemplar-GAN-Eye-Inpainting-master\utils.py", line 118, in read_image_list_for_Eyes
    if is_close or v[i]['opened'] < 0.60:

TypeError: '<' not supported between instances of 'NoneType' and 'float'

**Comment by zhangqianhui** [comment]
v[i]['opened'] is None ?

**Comment by SunHu1** [comment]
yes，I used the celeb_id_aligned dateset. When i test data.json，i found  some values of v[i]['opened'] is None. Then i meet that error.

**Comment by zhangqianhui** [comment]
"if is_close or v[i]['opened'] is None or v[i]['opened'] < 0.60:" may be work.

**Comment by wangziyan1234** [comment]
@zhangqianhui 您好， 请问～  如果想剔除掉数据集中的戴墨镜的图片  应该改哪里的代码呀

**Comment by wangziyan1234** [comment]
v[i]['opened'] is None   难道这句就是判断他有没有戴墨镜吗
