### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by wangziyan1234** [zhangqianhui/Exemplar-GAN-Eye-Inpainting-Tensorflow#6]
请问下 ~   如果我想输入一张睁眼的相片，输出一张闭眼 的，应该如何操作啊~    这是老师给的要求 ，小白不是很懂~   您有好的建议吗

**Comment by zhangqianhui** [comment]
你可以重新训练，用闭睛的照片训练，睁眼的测试

wangziyan1234 <notifications@github.com> 于2019年7月26日周五 下午1:09写道：

**Comment by wangziyan1234** [comment]
嗯嗯  谢谢啦






------------------ 原始邮件 ------------------
发件人: "JiChao Zhang"<notifications@github.com>; 
发送时间: 2019年7月27日(星期六) 上午9:46
收件人: "zhangqianhui/Exemplar-GAN-Eye-Inpainting-Tensorflow"<Exemplar-GAN-Eye-Inpainting-Tensorflow@noreply.github.com>; 
抄送: "去.听花落"<254793394@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zhangqianhui/Exemplar-GAN-Eye-Inpainting-Tensorflow] 你好 (#6)



你可以重新训练，用闭睛的照片训练，睁眼的测试 
 
 wangziyan1234 <notifications@github.com> 于2019年7月26日周五 下午1:09写道：

**Comment by wangziyan1234** [comment]
还有~  我下数据集老出问题 请问您这还有当时下载的数据集吗~   有的话能发我一份吗  邮箱我先贴上254793394@qq.com  非常感谢！！！

**Comment by zhangqianhui** [comment]
别人的数据集是不能随便转手的

**Comment by wangziyan1234** [comment]
这样啊  ~  还是谢谢啦

**Comment by wangziyan1234** [comment]
请问您的代码是在gpu上跑吗？

**Comment by zhangqianhui** [comment]
能阿

wangziyan1234 <notifications@github.com> 于2019年7月29日周一 下午2:39写道：
