### ISSUE TITLE
你好想问下局部判别器的结构

### ISSUE THREAD

**Issue by charmingjin** [zhangqianhui/Exemplar-GAN-Eye-Inpainting-Tensorflow#7]
大佬好，我看您重写的代码中，判别器分为了局部和整体两个判别器，在全局判别器的时候，传入了原图和参照图，但是对于局部判别器只传入了原图的眼睛。所以我想问下大佬，如果按照cgan的思想，不应该也要将原图的眼睛部分和参照图concat在一起再一起传入局部判别器吗 ？ 谢谢

**Comment by zhangqianhui** [comment]
you can see the code https://github.com/zhangqianhui/GazeCorrection

**Comment by charmingjin** [comment]
您好，我看了您提供的链接，很nice。但是我发现判别器和这篇实现上有所区别。您提供的文章中label是由原图经过self.encode得到的。这篇文章中的label则是指另一张没有闭眼的图片。在您的文章代码的实现中，local discriminator和global discriminator的输入都没有label，两者得到特征后再和label concat在一起再经过全连接。  而这篇文章中，global discriminator的输入是label和原图，而local discriminator 则只有局部的恢复图没有label，最后将两者concat一起。因为我没有见过cgan应用于local和global判别器，所以我想问为什么这篇文章没有采用和您将斜视变成正视中一样的判别器的流程。谢谢

**Comment by zhangqianhui** [comment]
This differenece make no sense. You can test it
