### ISSUE TITLE
运行出现了点问题，想请教一下。

### ISSUE THREAD

**Issue by a694387892** [zhangqianhui/Exemplar-GAN-Eye-Inpainting-Tensorflow#9]
您好！您的程序对我来说很有学习价值，谢谢您的分享，但是遇到了一些问题需要请教一下您，我的环境是3.7的，把print语法改了之后出现了以下问题，
  File "D:\Exemplar-GAN-Eye-Inpainting-Tensorflow-master\ExemplarGAN.py", line 42, in build_model_GAN
    self.x_tilde = self.encode_decode(self.incomplete_img, self.exemplar_images, 1 - self.img_mask, self.exemplar_mask, reuse=False)
  File "D:\Exemplar-GAN-Eye-Inpainting-Tensorflow-master\ExemplarGAN.py", line 228, in encode_decode
    instance_norm(conv2d(x_var, output_dim=64, k_w=7, k_h=7, d_w=1, d_h=1, name='e_c1'), scope='e_in1'))
  File "D:\Exemplar-GAN-Eye-Inpainting-Tensorflow-master\ops.py", line 24, in conv2d
    conv = tf.nn.conv2d(input_, w, strides=[1, d_h, d_w, 1], padding=padding)
TypeError: Value passed to parameter 'input' has DataType int32 not in list of allowed values: float16, bfloat16, float32, float64
这是哪里出问题了，需要怎么修正呢

**Comment by zhangqianhui** [comment]
TypeError: Value passed to parameter 'input' has DataType int32 not in list of allowed values: float16, bfloat16, float32, float64. You can check the datatype
